name: CI/CD pipeline

on:
  push:
    branches:
      - main
      - dev

env:
  PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip

jobs:
  show_infos:
    runs-on: ubuntu-latest
    steps:
      - name: Show application info
        run: |
          echo "Application = ${{ vars.APP_NAME }}"
          echo "Version = ${{ vars.APP_VERSION }}"
          echo "Développeur = ${{ vars.DEV_NAME }}"

  build_app:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Build application
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python -m py_compile calculatrice.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pycache
          path: __pycache__/
          retention-days: 1

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    needs: build_app
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cache Pip
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest test_calculatrice.py -v --junitxml=report.xml
          echo "Tests réussis"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml
          retention-days: 1

  show_report:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: download report
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: Display report
        run: cat report.xml

  deploy:
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker build
        uses: docker/setup-buildx-action@v3

      - name: Set up docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/calculatrice:latest

      - name: logout
        if: always()
        run: docker logout
